config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :trailheads
  end

  resources :trailheads do
    collection do
      post "email"
      get "map"
      get "fusion"
      get "wall"
    end
  end

  root :to => "home#index"

  get "bootleg", to: "home#bootleg"

  match "/dj" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trailheads

  def label
    email
  end
  
  def to_s
    email.split('@')[0]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @trailheads = @user.trailheads.order('id desc')
    render "trailheads/index"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save        
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
.row
  .col-md12
    %h3 Trail Editors

    %table.table.table-striped
      %tr
        %th Email
        %th Trailheads
        %th    
        

      - @users.each do |user|
        %tr
          %td= link_to user.email, user
          %td= user.trailheads.count
          %td.text-right
            = link_to 'Edit', edit_user_path(user), class: 'btn-edit'
            = link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn-delete'

    %br

    = link_to 'New User', new_user_path, class: 'btn-new'

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%row.col-md-12.container

  %div.col-md-12.headline.container-fix
    %h1 Trailheads Photographed by #{@user.email}

  %div.col-md-12.dashboard.container-fix
    %div.btn-group.actions
      = link_to "Download OpenTrails Data (GeoJSON)", trailheads_path(format: :json), class: 'btn btn-primary'
      %div.btn.btn-primary Share Trailheads with Park Agencies
      %div.btn.btn-primary
        = link_to 'Document a new Trailhead', new_trailhead_path

  -# %div.col-md-12.container-fix
  -#   %div.col-md-4.column-header
  -#     %h2.h3 Trailhead Photo
  -#   %div.col-md-4.column-header
  -#     %h2.h3 Location
  -#   %div.col-md-4.column-header
  -#     %h2.h3 Attributes


  - @trailheads.each do |trailhead|
    %div.col-md-12.trailhead-box.container-fix
      %div.col-md-4.photo-box
        = image_tag (trailhead.photo.url || "trailheadit_hq.jpg"), class: "img-responsive"
      %div.col-md-4.location-box
        .trailhead-map(id="trailhead-map-#{trailhead.id}")
        :javascript
          L.mapbox.accessToken = 'pk.eyJ1IjoidHJhaWxoZWFkbGFicyIsImEiOiJRNEU4VWFNIn0.IT_1YvYqery8yDIQZFDQqw';
          var myMap = L.mapbox.map('trailhead-map-#{trailhead.id}', 'trailheadlabs.63dd9d04')
          myMap.setView([#{trailhead.latitude}, #{trailhead.longitude}], 18);
          var marker = L.marker([#{trailhead.latitude}, #{trailhead.longitude}]).addTo(myMap);
      %div.col-md-4.details-box
        %ul
          %li= trailhead.name
          %li
            - if trailhead.restrooms
              ="Restrooms available on site"
            - else
              ="No restrooms available here"
          %li
            - if trailhead.drinking_water
              ="There is drinking water on site"
            - else
              ="No drinking water is available here"
          %li
            - if trailhead.parking
              ="There is parking on site"
            - else
              ="No parking is available here"
          %li
            - if trailhead.kiosk
              ="There is trail information present on site"
            - else
              ="No information is available here"
        = link_to 'Edit', edit_trailhead_path(trailhead), class: "btn btn-primary btn-block"
        = link_to 'Delete', trailhead, :method => :delete, class: "btn btn-danger btn-block"
  %br