config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :trailheads
  end

  resources :trailheads do
    collection do
      post "email"
      get "map"
      get "fusion"
      get "wall"
    end
  end

  root :to => "home#index"

  get "bootleg", to: "home#bootleg"

  match "/dj" => DelayedJobWeb, :anchor => false, via: [:get, :post]
end

app/views/layouts/_footer.html.haml
%br
%br
%hr.dark
.row
  .col-sm-12
    .landing.text-center
      %h3
        Hacked Together For
      %h2
        = link_to "The National Day of Civic Hacking 2014", "http://www.hackforchange.org"
      %br
      %h3 With Love From
      %br
.row
  .col-xs-4.col-sm-2.col-sm-offset-3
    = link_to "http://www.trailheadlabs.com" do
      = image_tag "thl_profile.png", class: "img-responsive"
  .col-xs-4.col-sm-2
    = link_to "http://www.codeforportland.org" do
      = image_tag "pdx_profile.png", class: "img-responsive"
  .col-xs-4.col-sm-2
    = link_to "http://www.codeforamerica.org" do
      = image_tag "cfa_profile.png", class: "img-responsive"

%br
%br
.row
  .col-xs-12.text-center
    %h3
      = link_to "Fork us on GitHub!", "https://github.com/CodeForPortland/trailheadit"
      
%br
%hr
.row
  .col-xs-12.text-center
    :erb
      This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>
      

app/views/layouts/_messages.html.haml
- if flash.any?
  .row
    .col-md-12

      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
            %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
            = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to root_path, class: 'navbar-brand' do
      TrailEditor
      - if Rails.env.staging?        
        Staging
  .collapse.navbar-collapse
    %ul.nav.navbar-nav.pull-right
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li
  = link_to 'Trailheads', trailheads_path
%li
  = link_to 'Map', map_trailheads_path
%li
  = link_to 'Add a Trailhead', new_trailhead_path
%li
  = link_to trailheads_path(format: :json) do    
    Download OpenTrails
%li
  = link_to "Open on GeoJSON.io", 
    "http://geojson.io/#data=data:text/x-url,#{trailheads_url(format: :json)}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    :erb
      <meta name="mobile-web-app-capable" content="yes">
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="apple-mobile-web-app-title" content="TrailEditor">
      <meta name='apple-mobile-web-app-status-bar-style' content='black'>
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0, user-scalable=no, minimal-ui"}
    %title= content_for?(:title) ? yield(:title) : 'Trail Editor : Help Locate Trailheads : Support Open Data'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Trail Editor'}"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    :erb
      <script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.js'></script>
      <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.css' rel='stylesheet' />
      <script src='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
      <link href='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
      <link href='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />

      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-47793966-3', 'traileditor.org');
        ga('send', 'pageview');

      </script>

      <!-- CARTODB -->
      <script src="http://libs.cartocdn.com/cartodb.js/v3/3.13/cartodb.core.js"></script>
  %body
    = render 'layouts/navigation'

    - if content_for :pre_container
      = yield :pre_container

    .container.main
      = render 'layouts/messages'
      = yield
      #footer
        = render "layouts/footer"